/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: Serious Black 19 (https://sketchfab.com/seriousblack_19)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/nikon-d5600-36194b93f54d45909587a3750f84402c
Title: Nikon D5600
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.metal} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.metal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
